# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Review
  displayName: Run load
  jobs:
  - job: Review
    displayName: Review
    variables:
      PROJECT_NAME: "sdsd"
    pool:
      vmImage: 'ubuntu-18.04'
    container: thelazycoder/neoload-controller-cli:latest
    steps:
    - script: /bin/sh /home/neoload/entrypoint.sh
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)