# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  variables:
  nlw_token: $(secret_nlw_token)
  zone_code: pimnV
  wksp: $(Pipeline.Workspace)/s
  zip_file_url: "https://github.com/paulsbruce/neoload-as-code/raw/NewExamplesRuntime/projects/example_2_0_runtime/Archive.zip"

stages:
- stage: PullNLProject
  displayName: Grab public sample NeoLoad project
  jobs:
  - job: Pull
    displayName: Pull
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - bash: |
        rm -rf $(wksp)/neoload_project
        mkdir $(wksp)/neoload_project
        curl $(zip_file_url) --output $(wksp)/neoload_project/project.zip
- stage: Run NeoLoad project
  displayName: Run load
  jobs:
  - job: Run
    displayName: Run
    variables:
      PROJECT_NAME: "sdsd"
    pool:
      vmImage: 'ubuntu-18.04'
      container: neoload_runner1
      steps:
      - script: |
        docker run --rm \
              -v "$(Build.Repository.LocalPath)/neoload-project/archive":/neoload-project \
              -e SCENARIO_NAME=smoke-test \
              -e NEOLOADWEB_TOKEN=<Your Token> \
              -e TEST_NAME=CI-smoke \
              -e CONTROLLER_ZONE_ID=<Your ZoneID>  \
              -e LG_ZONE_IDS=ZoneID:LG count1,ZoneID2>:LG count2  \
              neotys/neoload-web-test-launcher:latest;